name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.13

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Build
        run: go build cmd/status-reciever/main.go
